name: Build new package release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  PACKAGE: linux-lts66
  PACKAGER: 'bemxio <bemxiov@protonmail.com>'

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      volumes:
        - /:/__host_root

    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - name: Install dependencies and clone Git repository
        run: |
          pacman -Syu --noconfirm base-devel git

          git config --global --add safe.directory "$(pwd)"
          git clone --recursive "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" .

      - name: Export current and last built version
        run: |
          LAST_BUILT_VERSION=$(grep "^pkgver=" "$PACKAGE/PKGBUILD" | cut -d"=" -f2)
          git submodule update --remote
          CURRENT_VERSION=$(grep "^pkgver=" "$PACKAGE/PKGBUILD" | cut -d"=" -f2)

          echo "Last built version: $LAST_BUILT_VERSION"
          echo "Current version: $CURRENT_VERSION"

          echo "LAST_BUILT_VERSION=$LAST_BUILT_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Create dedicated user for build and signage
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION || github.event_name == 'workflow_dispatch' }}
        run: |
          cd "$PACKAGE"

          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/builder

          echo "${{ secrets.GPG_PRIVATE_KEY_ENCRYPTED }}" | base64 -d >> private.key.gpg
          gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --decrypt private.key.gpg | \
            sudo -u builder gpg --batch --import

          sudo -u builder gpg --batch --locate-keys torvalds@kernel.org
          sudo -u builder gpg --batch --locate-keys gregkh@kernel.org

          echo allow-loopback-pinetry >> /home/builder/.gnupg/gpg-agent.conf
          sudo -u builder gpg-connect-agent reloadagent /bye

          chown -R builder .

      - name: Free up space
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION || github.event_name == 'workflow_dispatch' }}
        run: |
          df -h
          rm -rf /__t/* /__host_root/{usr/share/dotnet,usr/local/lib/android,opt/ghc,opt/hostedtoolcache/CodeQL}
          df -h

      - name: Build packages
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION || github.event_name == 'workflow_dispatch' }}
        run: |
          sudo -u builder PACKAGER="$PACKAGER" MAKEFLAGS="-j$(nproc)" makepkg --dir "$PACKAGE" --noconfirm --syncdeps

      - name: Sign packages and create package repository
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION || github.event_name == 'workflow_dispatch' }}
        run: |
          mkdir "$PACKAGE-repo" && cd "$PACKAGE-repo"
          chown -R builder .

          cp ../"$PACKAGE"/*.pkg.tar.zst .
          cp ../index.html .

          for file in *.pkg.tar.zst; do
            sudo -u builder gpg --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
              --output "${file}.sig" --detach-sign "${file}"
          done

          sudo -u builder repo-add "$PACKAGE.db.tar.zst" *.pkg.tar.zst
          sudo -u builder gpg --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
            --output "$PACKAGE.db.tar.zst.sig" --detach-sign "$PACKAGE.db.tar.zst"

      - name: Upload repository as artifact
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PACKAGE }}-repo/

      - name: Deploy to GitHub Pages
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION || github.event_name == 'workflow_dispatch' }}
        uses: actions/deploy-pages@v4

      - name: Update submodules
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add "$PACKAGE"
          git commit -m "$CURRENT_VERSION"
          git push origin main
